config/routes.rb
FankuiB::Application.routes.draw do

  resources :forumdisplays

  resources :messages

  resources :solutions

  resources :cases

  resources :searches

  match 'good' => 'cases#good'

  get "session/follow"
  get "session/keep"
  

  get 'home/show'
  get 'home/autocomplete_user_email'
  get 'home/feed'
  
  match 'ajax/new' => 'ajax#new'
  match 'ajax/edit' => 'ajax#edit'
  match 'ajax/answer' => 'ajax#answer'
  match 'notice/false' => 'ajax#notice' 

  match 'mail' => 'home#mail'
  
  match 'sign' => 'ajax#sign'

  resources :reviews

  resources :presents, :except => :show
  
  match ':year/:month/:day/:id' => "presents#show", :as => 'present', :constraints => { :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :invitations => 'user/invitations' }

  resources :invitations

  resources :users do
    member do
      get "followers"
      get "favorites"
      get "messages"
    end
  end
    
  root :to => "home#index"

  resources :home, :path => "t" do
    collection do
      get :index
    end
  end

end

app/models/present.rb
# coding: utf-8
class Present < ActiveRecord::Base
  
    has_many :review
    
    mount_uploader :fileatt, FileattUploader
    
    
    def level_s
      case self.level
            when 1
              return 'VIP'
            when 2
              return '高'
            when 3
              return '中'
            when 4
              return '低'
            else
              return nil
            end
    end


    def cause_s
      case self.cause
            when '1'
              return '用户设置问题'
            when '2'
              return '其他'
            else
              return self.cause
            end
    end

    def type
      case self.question_type
            when 1
              return 'Internet Explorer'
            else
              return nil
            end
    end
    
    #计数器
    
    def count!
      uids = Rails.cache.read("Present:user_count:#{self.id}")
      
      if uids.blank?
        uids = 1
      else
        uids += 1
      end
      
      Rails.cache.write("Present:user_count:#{self.id}",uids)
    end
    
    def count
      uids = Rails.cache.read("Present:user_count:#{self.id}")
      return uids      
    end
    
    # 检查用户是否看过
    # result:
    #   0 读过
    #   1 未读
    #   2 最后是用户的回复
    def user_readed?(user_id)
      uids = Rails.cache.read("Present:user_read:#{self.id}")
      if uids.blank?
        if self.last_reply_user_id == user_id || self.user_id == user_id
          return 2
        else 
          return 1
        end
      end

      if uids.index(user_id)
        return 0
      else
        if self.last_reply_user_id == user_id || self.user_id == user_id
          return 2
        else 
          return 1
        end
      end
    end    
    
    
    # 记录用户读过
    def user_readed(user_id)
      uids = Rails.cache.read("Present:user_read:#{self.id}")
      if uids.blank?
        uids = [user_id]
      else
        uids = uids.dup
      end

  		uids << user_id
      Rails.cache.write("Present:user_read:#{self.id}",uids)
    end
    
    # helper method to generate redis keys
    def redis_key(str)
      "Present:#{self.id}:#{str}"
    end
end

app/controllers/presents_controller.rb
class PresentsController < InheritedResources::Base
  
  def index
    
       @presents = Present.all

    @time = []
    now   = Time.now.to_date
    
    @case = []
    
    @c_c = 9
    
    for i in 0..@c_c
      @time[i] = now + i.day - @c_c.day
      @case[i] = Present.find(:all, :conditions => "request_time = '#{@time[i]}'").count
    end

    if params[:resolve]
    @presents = Present.find(:all, :conditions => "resolve = #{params[:resolve]}")
    end
  end
  
  def new
    @present = Present.new

    respond_to do |format|
      format.html # new.html.erb
      format.js 
    end
  end
  
  def show
    @present = Present.find(params[:id]) 
    @present.count!
  end
  
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/views/presents/_form.html.erb
<%= form_for(@present) do |f| %>
  <% if @present.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@present.errors.count, "error") %> prohibited this present from being saved:</h2>

      <ul>
      <% @present.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="main_wrapper">
	<tbody>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '标题' %>
					    <%= f.text_field :title %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element"  id='new_present'>
					<div class="input">
					    &nbsp;&nbsp;&nbsp;&nbsp;<%= f.label '优先级' %>
					    <%= f.select :level ,{'VIP' => '1', '高'=> '2','中' => '3', '一般' => '4'} %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '问题描述' %><br />
						<%= f.cktext_area :description, :toolbar => 'Basic', :width => 600, :height => 300 %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '问题原因' %>
						<%= f.select :cause ,{'系统原因' => '1', '其他原因' => '2'} %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '原因描述' %>
					    <%= f.cktext_area :cause_detail, :toolbar => 'Basic', :width => 600, :height => 300 %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '解决方案' %>
					    <%= f.cktext_area :solution, :toolbar => 'Basic', :width => 600, :height => 300 %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.label '备注' %>
					    <%= f.text_field :note %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '问题类型' %>
					    <%= f.number_field :question_type %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label :fileatt %>s
					    <%= f.file_field :fileatt %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '问题解决' %>
					<%= f.check_box :resolve %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
    					<%= f.label '用户' %>
    					<%= f.number_field :user_id  %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '提交日期',:id => 'xwj' %>
					    <%= f.datetime_select :request_time %>
					</div>
				</div>
			</td>
		</tr>
				<%= f.hidden_field :replies_count,:value => '0' %>
	</tbody>
</table>


  <div class="input">

  </div>

<div class="group">

</div>

<div class="group buttons no_header ">
<table >
<tbody>
<tr>
<td>
<div class="element">
<div class="input">
	<button class="submit ui-submit-button" type="submit">提交</button>
</div>
</div>
</td>
</tr>
</tbody>
</table>
</div>

<% end %>

app/views/presents/_main.html.erb
<div>
	<p>
	  <h1>
		<b>标题:</b>
		<%= @present.title %>
	  </h1>
	<h2>
		(已解决)
	</h2>
	</p>
</div>
<div>
	<div id="sidebar">产品类型:</div>
  	<div id="content">Internet Explorer产品</div>
</div>
	<div>
			<div id="sidebar">项目：</div>
		  	<div id="content">未指定</div>
	</div>
<div>
	<div id="sidebar">优先级:</div>
  	<div id="content"><%= @present.level_s %></div>
</div>
<div>
	<div id="sidebar">描述:</div>
  	<div id="content"><%=raw @present.description %></div>
</div>
<div>
	<div id="sidebar">问题原因:</div>
  	<div id="content"><%= @present.cause_s %></div>
</div>
<div>
	<div id="sidebar">原因描述:</div>
  	<div id="content"><%=raw @present.cause_detail %></div>
</div>
<div>
	<div id="sidebar">解决方案:</div>
  	<div id="content"><%=raw @present.solution %></div>
</div>
<div>
	<div id="sidebar">文档附件:</div>
  	<div id="content"><%= link_to @present.fileatt.to_s.split('/').last, @present.fileatt.to_s if @present.fileatt.to_s %>
	(<%= number_to_human_size(@present.fileatt.size, :precision => 2)  %>)
	</div>
</div>
<div>
	<div id="sidebar">备注:</div>
  	<div id="content">暂无备注</div>
</div>
<div>
		<div id="sidebar">截止时间：</div>
	  	<div id="content">-</div>
</div>
<div>
	<div id="sidebar">用户:</div>
  	<div id="content"><%= User.first.email %></div>
</div>
<div>
	<div>留言：</div>
</div>
<div>

app/views/presents/_nav_tool.html.erb
<div id="jive-body-sidebarcol-container">
	
	<p>
		<p><%= link_to '添加答案',ajax_answer_path(:case => params[:id]),:class => "ajax btn primary" %></p>
		<p><%= link_to '新问题',ajax_new_path,:class => "ajax btn primary" %></p>
		<p><%= link_to '收  藏',session_keep_path(:present_id => params[:id]),:class => "btn primary" %></p>
		<p><%= link_to '分 享','#inline_content',:class => "inline btn primary" %>	</p>
		<p><%= link_to '类似案例','#',:class => "btn primary" %></p>
		<p><%= link_to '日  志','#',:class => "btn primary" %></p>
		<p><%= link_to '编辑该问题',ajax_edit_path(:case_id => params[:id]),:class => "ajax btn primary" if !params[:id].blank? %></p>
	</p>

</div>

app/views/presents/_present_bar.html.erb
<% content_for :bar do %>
<li class="active">
	<a href="/">首页</a>
</li>
	<li class="active">
			<%= link_to '家庭 | 个人', cases_path %>
			<span class="notch">
				<span class="inner">&nbsp;</span>
			</span>
	</li>
	<li class="active">
		<%= link_to '商务 | 工作', cases_path %>
	</li>
<li class="active">
	<%= link_to '帮助', '/admin' %>
</li>
<% end %>

<% content_for :bar do %>
<% end %>

app/views/presents/edit.html.erb
<%= render 'present_bar' %>

<h1>Editing present</h1>

<%= render 'form' %>

<%= link_to 'Show', @present %> |
<%= link_to 'Back', presents_path %>

app/views/presents/index.html.erb
<%= render 'present_bar' %>

<div id="container">

<div id="jive-body-maincol-container">
	
<p>
	<%= link_to '全部', presents_path %> |
	<%= link_to '已完成', presents_path(:resolve => 'true') %> |
	<%= link_to '未完成', presents_path(:resolve => 'false') %>
</p>

<div id="orders_chart2" style="width: 600px; height: 300px;"></div>

<table class="pretty">
  <!-- Orders table code here -->
</table>


<script type="text/javascript" charset="utf-8">
$(function () {

	new Highcharts.Chart({
    chart: { renderTo: 'orders_chart2' },
    title: { text: '问题解决数量' },
    xAxis: { categories: [
	
		<% @time.each do |timeday| %>
			'<%= timeday %>',
		<% end %>
						  ] },
    yAxis: {
      title: { text: '笔数'}
    },
    series: [{
      data: [
				<% @case.each do |caseday| %>
					<%= caseday %>,
				<% end %>
			]
    }]
  });
});
</script>



<div class="actions_wrapper">

	<ul class="content_actions">
		项目历史</br>
	</ul>
	<ul class="content_bctions">
		<table>
			<tr>
				<td></td>
				<td></td>
				<td>优先</td>
				<td>标题</td>
				<td>产品类型</td>
				<td>时间</td>
				<td>浏览</td>
			</tr>

				<% @presents.each do |present| %>
			<tr>
				<td><%= present.user_readed?(current_user.id) if user_signed_in?  %></td>
				<td><%= '已解决' if present.resolve %></td>
				<td><%= present.level_s %></td>
				<td><%= link_to truncate(present.title,:length => 40), present_slug(present) %></td>
				<td><%= present.type %></td>		
				<td><%= present.created_at.to_date %></td>
			    <td><%= link_to '编辑', edit_present_path(present) if user_signed_in? %></td>
			    <td><%= link_to '下载附件', present.fileatt.to_s if present.fileatt.to_s %></td>
				<td><%= present.count %></td>
			</tr>
				<% end %>
		</table>
	</ul>
</div>
</br>


<%= link_to '提交一个新问题', new_present_path %>

</div>


<%= render 'nav_tool' %>

</div>

app/views/presents/new.html.erb
<%= render 'present_bar' %>

<h1>提交一个新问题</h1>

<%= render 'form' %>

app/views/presents/show.html.erb
<%= render 'present_bar' %>

<!-- UserReaded? <%= @present.user_readed(current_user.id) if user_signed_in?  %> -->

<div id="container">
	<p id="notice"><%= notice %></p>
	
	<div style='display:none'>
		<div id='inline_content' style='padding:10px; background:#fff;'>
			分享到。。
		</div>
	</div>
	
	
	
	
	<div id="jive-body-maincol-container">
		<div>
		<h2>
		<%= @present.title %>
		</h2>
		</div>
		<div>
		<strong> <%= @present.count %>&nbsp;Views </strong>
		<strong>0 Replies</strong>
		<a class="localScroll" href="/message/16590556?tstart=0#16590556">Latest reply</a>
		: 2011-10-31 下午5:56 by matteochirco926
		</div>
		
		<div class="jive-thread-info font-color-meta">
			适用于：Internet Explorer产品
		</div>
		
		
		<div class="jive-thread-info font-color-meta">
			项目： 暂无分类 | 
			优先级：<%= @present.level_s %> |
			项目截止日期： <%= Time.now.to_date + 2.day %>
		</div>
		
		<div class="jive-thread-info font-color-meta">
			<h3>问题描述</h3>
			<%=raw @present.description %>
		</div>
		
		<div class="jive-thread-info font-color-meta">
			<h3>发生原因</h3>
			<%=raw @present.cause_detail %>
		</div>
		
		<div class="jive-thread-info font-color-meta">
			<h3>解决方案</h3>
			<%=raw @present.solution %>
		</div>

			<div class="jive-thread-info font-color-meta">
				<h3>文档附件</h3>
				<% if !@present.fileatt.blank? %>
					<%= link_to @present.fileatt.to_s.split('/').last, @present.fileatt.to_s %>
					(<%= number_to_human_size(@present.fileatt.size, :precision => 2)   %>)
				<% else %>
				无附件
				<% end %>
			</div>
			

		  	<div class='pinglun'>

				<% if @present.review != [] %>

				<% @present.review.each do |review| %>
				<p>
					<%= link_to (image_tag review.user.people , :size => '50x50'), user_path(review.user)%>
					<%= review.content %></br>
					由 <%= review.user.email %> 发布. <%= review.created_at.to_date %>
				</p>
				<% end %>

				<% else %>

				暂时还没有评论

				<% end %>
				<div>   
					<%= link_to '增加一条留言',new_review_path(:present => params[:id]),:remote => true,:class => "btn primary" if user_signed_in? %>
					<div id='edit_window'></div>
				</div>
			</div>
	</div>
	
	<%= render 'nav_tool' %>

</div>