config/routes.rb
FankuiB::Application.routes.draw do

  resources :forumdisplays

  resources :messages

  resources :solutions

  resources :cases

  resources :searches

  match 'good' => 'cases#good'

  get "session/follow"
  get "session/keep"
  

  get 'home/show'
  get 'home/autocomplete_user_email'
  get 'home/feed'
  
  match 'ajax/new' => 'ajax#new'
  match 'ajax/edit' => 'ajax#edit'
  match 'ajax/answer' => 'ajax#answer'
  match 'notice/false' => 'ajax#notice' 

  match 'mail' => 'home#mail'
  
  match 'sign' => 'ajax#sign'

  resources :reviews

  resources :presents, :except => :show
  
  match ':year/:month/:day/:id' => "presents#show", :as => 'present', :constraints => { :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :invitations => 'user/invitations' }

  resources :invitations

  resources :users do
    member do
      get "followers"
      get "favorites"
      get "messages"
    end
  end
    
  root :to => "home#index"

  resources :home, :path => "t" do
    collection do
      get :index
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  
  def formuser(id)
    return User.find_by_id("#{id}")
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < InheritedResources::Base
  
  
  
  def create
    params[:message][:msg_to_id] = User.find_by_email(params[:message][:msg_to_id]).id
    params[:message][:request_ip] = request.remote_ip
    
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save!
        format.html { redirect_to :back, notice: 'Chapter was successfully created.' }
      else
        format.html { redirect_to :back, notice: 'Error' }
      end
    end
  end
  
  
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>

  <div class="field">
    <%= f.hidden_field :msgfrom_id,:value => current_user.id %>

  </div>
  <div class="field">
    <%= f.label :msg_to_id %><br />
	 <%=f.autocomplete_field 'msg_to_id', home_autocomplete_user_email_path %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Msgfrom</th>
    <th>Msg to</th>
    <th>Content</th>
    <th>Delete</th>
    <th>Related</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.msgfrom_id %></td>
    <td><%= message.msg_to_id %></td>
    <td><%= message.content %></td>
    <td><%= message.deleted %></td>
    <td><%= message.related %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Msgfrom:</b>
  <%= @message.msgfrom_id %>
</p>

<p>
  <b>Msg to:</b>
  <%= @message.msg_to_id %>
</p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>

<p>
  <b>Delete:</b>
  <%= @message.deleted %>
</p>

<p>
  <b>Related:</b>
  <%= @message.related %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>