config/routes.rb
FankuiB::Application.routes.draw do

  resources :forumdisplays

  resources :messages

  resources :solutions

  resources :cases

  resources :searches

  match 'good' => 'cases#good'

  get "session/follow"
  get "session/keep"
  

  get 'home/show'
  get 'home/autocomplete_user_email'
  get 'home/feed'
  
  match 'ajax/new' => 'ajax#new'
  match 'ajax/edit' => 'ajax#edit'
  match 'ajax/answer' => 'ajax#answer'
  match 'notice/false' => 'ajax#notice' 

  match 'mail' => 'home#mail'
  
  match 'sign' => 'ajax#sign'

  resources :reviews

  resources :presents, :except => :show
  
  match ':year/:month/:day/:id' => "presents#show", :as => 'present', :constraints => { :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :invitations => 'user/invitations' }

  resources :invitations

  resources :users do
    member do
      get "followers"
      get "favorites"
      get "messages"
    end
  end
    
  root :to => "home#index"

  resources :home, :path => "t" do
    collection do
      get :index
    end
  end

end

app/controllers/cases_controller.rb
class CasesController < InheritedResources::Base
  
  def index
       @presents = Case.all

    @time = []
    now   = Time.now.to_date
    
    @case = []
    
    @c_c = 9
    
    for i in 0..@c_c
      @time[i] = now + i.day - @c_c.day
      @case[i] = Present.find(:all, :conditions => "request_time = '#{@time[i]}'").count
    end

    if params[:resolve]
    @presents = Present.find(:all, :conditions => "resolve = #{params[:resolve]}")
    end
    
    @forum = Forumdisplay.all
    
  end

  def good
    solution = Solution.find(params[:solution_id])
    if solution.update_attributes!(:good_number => solution.good_number + 1)
      redirect_to :back, notice: 'Thanks you job.'
    end
  end
  
end

app/helpers/cases_helper.rb
# coding: UTF-8
module CasesHelper
  
  def expired_nn
    
    if @case.deadline.day <= Time.now.day
      return '已过期'
    end
    
  end

  
end

app/views/cases/_form.html.erb
<h2>发表新问题</h2>

<%= form_for(@case) do |f| %>
  <% if @case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

      <ul>
      <% @case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :deadline %>
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :product %>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id,:value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :project %>
    <%= f.text_field :project %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cases/edit.html.erb
<h1>Editing case</h1>

<%= render 'form' %>

<%= link_to 'Show', @case %> |
<%= link_to 'Back', cases_path %>

app/views/cases/index.html.erb
<%= render 'presents/present_bar' %>

<div id="container">

<div id="jive-body-maincol-container">
	
<p>
	<%= link_to '全部', presents_path %> |
	<%= link_to '已完成', presents_path(:resolve => 'true') %> |
	<%= link_to '未完成', presents_path(:resolve => 'false') %>
</p>

<div id="orders_chart2" style="width: 600px; height: 300px;"></div>

<table class="pretty">
  <!-- Orders table code here -->
</table>


<script type="text/javascript" charset="utf-8">
$(function () {

	new Highcharts.Chart({
    chart: { renderTo: 'orders_chart2' },
    title: { text: '问题解决数量' },
    xAxis: { categories: [
	
		<% @time.each do |timeday| %>
			'<%= timeday %>',
		<% end %>
						  ] },
    yAxis: {
      title: { text: '笔数'}
    },
    series: [{
      data: [
				<% @case.each do |caseday| %>
					<%= caseday %>,
				<% end %>
			]
    }]
  });
});
</script>



<% @forum.each do |forum| %>

<div class="actions_wrapper">

	<ul class="content_actions">
		<%= forum.title %>
	</ul>
	<ul class="content_bctions">
		<table>
		  <tr>
		    <th>Title</th>
		    <th>Deadline</th>
		    <th>User</th>
		  </tr>

		<% forum.case.each do | view | %>
		  <tr>
			<td><%= format("%05d",view.id) %></td>
		    <td><%= link_to view.title,view %></td>
		    <td><%= view.deadline %></td>
		    <td><%= view.user.email %></td>
		    <td><%= (view.created_at. + 8.hour).to_s(:db) %></td>
		  </tr>
		<% end %>
		</table>
	</ul>
</div>

<% end %>
</br>


<%= link_to '提交一个新问题', new_case_path %>

</div>


<%= render 'presents/nav_tool' %>

</div>

app/views/cases/new.html.erb
<h1>New case</h1>

<%= render 'form' %>

<%= link_to 'Back', cases_path %>

app/views/cases/show.html.erb
<%= render 'presents/present_bar' %>

<%= render 'presents/nav_tool' %>


<div id="container">
	
	<div id="jive-body-maincol-container">
		<div>
			<h1><%= @case.title %></h1>
			<%= link_to '我也遇到了同样的问题','/same' %>
		</div>
		
		<div class="jive-thread-info font-color-meta">
			优先级: <%= @case.level_string %> | 
			过期:	<%= @case.expired? %> |
		   阅读次数:
		</div>
		
		<div class="jive-thread-info font-color-meta">
			适用于:  <%= @case.product %> |
			项目: <%= @case.project %> | 
			截止时间:  <%= @case.deadline %> |
			发布人:  <%= @case.user.email %>
		</div>
		
		<div class="jive-thread-info font-color-meta">
			<h3>问题描述</h3>
			<%= @case.description %>
		</div>
		

			<% if @case.solution.count != 0 %>
				<div class="jive-thread-info font-color-meta">
					<h3>有<%= @case.solution.count %>个答案</h3>
				</div>	
				<% @case.solution.order('good_number DESC').each do |solution | %>
				<div class="jive-thread-info font-color-meta">		
					<h4><%= solution.good_number %>人认为有帮助</h4>
					<%= link_to '投票',good_path(:solution_id =>solution) %>
					<h3>原因</h3>
					<%= solution.reason %>
					<h3>答案</h3>
					<%= solution.content %></br>
					</br>
					由<%= solution.user.email %>发表 , <%= solution.created_at.to_s(:db) %>
				</div>
				<% end %>
			<% else %>
		  		<div class="jive-thread-info font-color-meta">
		  			目前还没有答案，快来回答哦
		  		</div>
			<% end %>
	
		

		
		
		
		<div class='pinglun'>

			<% if !@case.review.blank? %>

			<% @case.review.each do |review| %>
			<p>
				<%= link_to (image_tag review.user.avatar , :size => '50x50'), user_path(review.user)%>
				<%= review.content %></br>
				由 <%= review.user.email %> 发布. <%= review.created_at.to_date %>
			</p>
			<% end %>

			<% else %>

			暂时还没有评论

			<% end %>
			<div>   
				<%= link_to '增加一条留言',new_review_path(:present => params[:id]),:remote => true,:class => "btn primary" if user_signed_in? %>
				<div id='edit_window'></div>
			</div>
		</div>

		
		
		<%= link_to 'Edit', edit_case_path(@case) %> |
		<%= link_to 'Back', cases_path %>
	</div>
	

</div>