config/routes.rb
FankuiB::Application.routes.draw do

  resources :forumdisplays

  resources :messages

  resources :solutions

  resources :cases

  resources :searches

  match 'good' => 'cases#good'

  get "session/follow"
  get "session/keep"
  

  get 'home/show'
  get 'home/autocomplete_user_email'
  get 'home/feed'
  
  match 'ajax/new' => 'ajax#new'
  match 'ajax/edit' => 'ajax#edit'
  match 'ajax/answer' => 'ajax#answer'
  match 'notice/false' => 'ajax#notice' 

  match 'mail' => 'home#mail'
  
  match 'sign' => 'ajax#sign'

  resources :reviews

  resources :presents, :except => :show
  
  match ':year/:month/:day/:id' => "presents#show", :as => 'present', :constraints => { :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :invitations => 'user/invitations' }

  resources :invitations

  resources :users do
    member do
      get "followers"
      get "favorites"
      get "messages"
    end
  end
    
  root :to => "home#index"

  resources :home, :path => "t" do
    collection do
      get :index
    end
  end

end

app/views/shared/_content_for_bar.erb
<% content_for :bar do %>
<% if user_signed_in? %>
<li class="active">
	<a href="/">首页</a>
</li>
<li class="active">
		<%= link_to '家庭 | 个人', cases_path %>
</li>
<li class="active">
	<%= link_to '商务 | 工作', cases_path %>
</li>
<li class="active">
	<%= link_to '帮助', '/admin' %>
</li>
<% else %>
<li class="active">
		<%= link_to '家庭 | 个人', presents_path %>
</li>
	<li class="active">
		<%= link_to '商务 | 工作', presents_path %>
	</li>	
<li class="active">
	<%= link_to '自助修复(beta)', '/admin' %>
</li>
<li class="active">
	<%= link_to '帮助', '/admin' %>
</li>
<% end %>
<% end %>

app/views/shared/_errors_messages.html.erb
<% [:notice, :alert, :error].each do |key| %>
	<% if flash[key] %>
		<div class="<%= key %>" id="erros_messages"><%= flash[key] %></div>
	<% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
	<ul>
		<li class="first">
			<%= link_to Settings.app_name, '/about' %>&nbsp;&nbsp;|&nbsp;&nbsp; 
			<%= link_to '版本历史', '/' %>&nbsp;&nbsp;|&nbsp;&nbsp; 
			<%= link_to 'BUG反馈', '/' %>&nbsp;&nbsp;|&nbsp;&nbsp; 
			<%= link_to 'Rss订阅', '/home/feed.rss' %>
		</li>
	</ul>
	<ul class="legal">
		<li><%=raw Settings.copyright_name %></li>
	</ul>
</div>



<script>
	$(document).ready(function(){
	//alret erros_messages
		$("#erros_messages").fadeTo(3000, 0);
	});
	
	
	//Examples of how to assign the ColorBox event to elements
	$(".group1").colorbox({rel:'group1'});
	$(".group2").colorbox({rel:'group2', transition:"fade"});
	$(".group3").colorbox({rel:'group3', transition:"none", width:"75%", height:"75%"});
	$(".group4").colorbox({rel:'group4', slideshow:true});
	$(".youtube").colorbox({iframe:true, innerWidth:425, innerHeight:344});
	$(".iframe").colorbox({iframe:true, width:"80%", height:"80%"});
	$(".inline").colorbox({inline:true, width:"50%"});
	$(".ajax").colorbox({ width:"50%"});
	$(".callbacks").colorbox({
		onOpen:function(){ alert('onOpen: colorbox is about to open'); },
		onLoad:function(){ alert('onLoad: colorbox has started to load the targeted content'); },
		onComplete:function(){ alert('onComplete: colorbox has displayed the loaded content'); },
		onCleanup:function(){ alert('onCleanup: colorbox has begun the close process'); },
		onClosed:function(){ alert('onClosed: colorbox has completely closed'); }
	});
	
	//Example of preserving a JavaScript event for inline calls.
	$("#click").click(function(){ 
		$('#click').css({"background-color":"#f00", "color":"#fff", "cursor":"inherit"}).text("Open this window again and this message will still be here.");
		return false;
	});
</script>

app/views/shared/_form.html.erb
<%= form_for(@present) do |f| %>



<table class="mini_wrapper">
	<tbody>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '标题' %>
					    <%= f.text_field :title %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element"  id='new_present'>
					<div class="input">
					    <%= f.label '优先级' %>
					    <%= f.select :level ,{'VIP' => '1', '高'=> '2','中' => '3', '一般' => '4'} %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input" id='mini_present'>
					    <%= f.label '问题描述' %>
						<%= f.text_field :description %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '问题类型' %>
					    <%= f.number_field :question_type %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="element" id='new_present'>
					<div class="input">
					    <%= f.label '上传附件' %>
					    <%= f.file_field :fileatt %>
					</div>
				</div>
			</td>
		</tr>
	</tbody>
	<%= f.hidden_field :replies_count,:value => '0' %>
</table>


  <div class="input">

  </div>

<div class="group">

</div>

<div class="group buttons no_header ">
<table >
<tbody>
<tr>
<td>
<div class="element">
<div class="input">
	<button class="submit ui-submit-button" type="submit">提交</button> <%= link_to '切换到完整模式',new_present_path %>
</div>
</div>
</td>
</tr>
</tbody>
</table>
</div>
<% end %>

app/views/shared/_head.html.erb
<div class="head">
	<div class="inner">
		<a class="logo" href="/">产品反馈系统</a>
		<ul id="mainnav">
			<%= yield :bar %>
		</ul>
		<ul id="tools">

			<li class="auth">
				<ul>
					<% if user_signed_in? -%> <!-- Provided by devise -->
					<li>

					</li>
				</ul>
			</li>
					<li id="usermenu" class="user">
											  
											<a class="avatar" href="<%= user_path(current_user) %>">
												<% if !current_user.people.blank? %>
													<%= image_tag(current_user.people,:size =>"27x27",:id => 'user_icon') %>
												<% else %>
													<%= image_tag('/images/none_logo.jpg',:size =>"27x27",:id => 'user_icon') %>
												<% end %>
											<span class="mask">&nbsp;</span>
											</a>
						<a class="name" onclick="$('#usermenu').toggleClass('open'); return false;" href="<%= users_path(current_user) %>"><%= current_user.email %></a>
						<span class="indicator" onclick="$('#usermenu').toggleClass('open'); return false;">&nbsp;</span>
						<ul class="menu">
						<li class="top">&nbsp;</li>
						<li class="logged_in_as">Hi,欢迎回来</li>
						<li class="divider">&nbsp;</li>
						<li class="logged_in_as"><%= link_to '我的收藏', favorites_user_path(current_user) %></li>
						<li class="logged_in_as"><%= link_to '我的好友', followers_user_path(current_user) %></li>
						<li class="logged_in_as"><%= link_to '我的私信', messages_user_path(current_user) %></li>						
						<li class="divider">&nbsp;</li>
						<li class="logged_in_as"><%= link_to '退出登录', destroy_user_session_path, :method => :delete %></li>
						<li class="btm">&nbsp;</li>
						</ul>
					</li>
										
					<% else %>
					<div style="float:right">
					<li>
					  <%= link_to '注册', new_user_registration_path %>
					</li>
					<li>
					<%= link_to '登陆',sign_path,:class => "ajax",:remote => true %>
					</li>
					</div>
				</ul>
			</li>
					<% end -%>
			<li class="search">
				<form method="post" action="/searches/">
				<label class="icon" for="gsrch">&nbsp;</label>
				<input id="search_keywords" type="text" autocorrect="off" spellcheck="false" autocomplete="off" maxlength="70" value="" name="title">
				</form>
			</li>
		</ul>
	</div>
</div>